# Inspired by cbkadal's repo

title:       "Operating Systems 2022-2 (ODD Semester 2021/2022)"
description: "Hello there!"
author:           "Kausar Meutuwah"
address:          "Depok"
sitemap:          "true"
urlweb:           "https://kausarme.github.io/os222/"
urlgithub:        "https://github.com/kausarme/os222/"
urlghpage:        "https://naufalpram.github.io/os222/"
