# Inspired by cbkadal's repo

title: "kausarme @ Operating System"
description: "Website Sistem Operasi Kausar"
baseurl: /os222
url: "https://kausarme.github.io/os222/"

copyright_year : 2022

author: "Kausar Meutuwah"
repository: "https://github.com/kausarme/os222/"

urlweb: "https://kausarme.github.io/os222/"
urlgithub: "https://github.com/kausarme/os222/"
urlghpage: "https://kausarme.github.io/os222/"

